server:
  port: 6377

spring:
  redis:
    password: Visionvera#3$4%5
    jedis:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: 1000
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
    cluster:
      nodes: 47.104.192.128:7000,47.104.192.128:7001,47.104.192.128:7002,45.33.47.39:7000,45.33.47.39:7001,45.33.47.39:7002
    timeout: 1000
    commandTimeout: 1000